[package]
authors = ["Davide Corradi <davide.corradi.dev@gmail.com>"]
edition = "2021"
name = "roe_asset_manager"
version = "0.1.0"

[dependencies]
roe_audio = {path = "../roe_audio"}
roe_graphics = {path = "../roe_graphics"}
roe_text = {path = "../roe_text"}
image = {version = "0.23.*"}