[workspace]
resolver = "2"
members = [
  "roe_math",
  "roe_os",
  "roe_app",
  "roe_shader",
  "roe_graphics",
  "roe_shape2",
  "roe_sprite",
  "roe_text",
  "roe_audio",
  "roe_assets",
  "roe_examples",
]
