[package]
name = "roe_shader"
version = "0.1.0"
authors = ["Davide Corradi <davide.corradi.dev@gmail.com>"]
edition = "2018"

[dependencies]
shaderc = "0.6"

[dev-dependencies]
galvanic-assert = "0.8.7"

[[bin]]
name = "shader_compilation"
path = "examples/shader_compilation.rs"
