[package]
authors = ["Davide Corradi <davide.corradi.dev@gmail.com>"]
edition = "2021"
name = "roe_shader"
version = "0.1.0"

[dependencies]
shaderc = "0.7.*"

[dev-dependencies]
galvanic-assert = "0.8.*"

[[example]]
name = "shader_compilation"
path = "examples/shader_compilation.rs"
