[package]
authors = ["Davide Corradi <davide.corradi.dev@gmail.com>"]
edition = "2018"
name = "roe_audio"
version = "0.1.0"

[dependencies]
alto = "3.0.4"
lazy_static = "1.4.0"

[dev-dependencies]
galvanic-assert = "0.8"

[build-dependencies]
cmake = "0.1.40"
