[package]
authors = ["Davide Corradi <davide.corradi.dev@gmail.com>"]
edition = "2018"
name = "roe_examples"
version = "0.1.0"

[dependencies]
roe_app = {path = "../roe_app"}
roe_math = {path = "../roe_math", features = [
  "serde-serialize",
]}
roe_gfx = {path = "../roe_gfx"}
rand = "0.7"
num = {version = "0.3"}